import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ESU",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="scroll-smooth" lang="en">
      <body className={inter.className}>
        <div className="fixed top-0 w-full z-50 bg-white">
          <Navbar />
        </div>
        <div className="pt-[89px] md:pt-[96px]">
          {/* Add padding-top to avoid overlap from fixed navbar */}
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
